### PR TITLE
[WIP] Refactor `Cursor` struct

### PR DESCRIPTION
**Pull request by smolck**
Currently, this does not quite work, but the general framework is there. The problem is printing the output (it doesn't work quite right), and I assume it's because of how `Clone` and the `reset` function for `Cursor` are implemented in this branch (can't clone the terminal cursor, so I've created a new one, which I don't think is working. Need a way to copy over/clone the current `TerminalCursor`).

Also, I may need to rebase with master: should be able to do so once I work out the conflicts.

### CODE REVIEW

**Comment by sigmaSd** [comment]
thanks for your work!

does this work?
```rust
let cursor = TerminalCursor::now();
self.goto_cursor();
```
worst case we can use Option and take trick to move the cursor around, exp:
```rust
struct Cursor {
 inner_cursor: Option <TerminalCursor>,
}
impl Clone for Cursor {
fn clone(&self) {
 let cursor = self.inner_cursor.take()
//....
}

**Comment by sigmaSd** [comment]
Actually we probably can use `mem::replace` instead of the option trick

**Comment by smolck** [comment]
@sigmaSd `TerminalCursor::now()` works just as expected, making this refactor functional (once I push the change here in a sec). We may want to rename some function names though, either now or later; what do you think of the ones I have currently (also, please checkout my comments in cursor.rs if you haven't already)?

**Comment by smolck** [comment]
One minute, I'm fixing my terrible mistakes with how I did this branch...

**Comment by smolck** [comment]
@sigmaSd I'm gonna close this PR and open a new one with my other branch. I messed up the rebase on master, and I don't think I could (easily) fix it without doing this.

**Pull request closed without merging**
