### PR TITLE
Implement Autosync

### PR DESCRIPTION
**Pull request by sigmaSd**
Implements Autosync instead of the need of manually using `:sync` after each edit in external editor 

@fdncred, I'm pinging in you in case you want to test this feature, since its based on your idea.

The workflow is now like this:
1- :edit atom/code or manually open `$TEMP/irust/src/main_extern.rs`

Any changes to this file will immediately be reflected on irust (after saving)

### CODE REVIEW

**Comment by fdncred** [comment]
I tested and it panics when I hit save. Here's the back trace.
```
-----------------------------------------------Welcome to IRust-----------------------------------------------
In: fn factorial(n: usize) -> usize {
..:     match n {
..:         1 => 1,
..:         n => n * factorial(n - 1),
..:     }
..: }

In: :type factorial
fn item `fn(usize) -> usize {factorial}`
In: factorial(12)
Out: 479001600

In: :edit code-insiders
waiting for code-insiders...
Ok!
In: thread 'main' panicked at 'IRust Out: Custom("main.rs file corrupted, resetting irust..")', src\main.rs:19:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
   9: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
  10: std::panicking::begin_panic_handler
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
  11: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:85
  12: core::option::expect_none_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\option.rs:1269
  13: core::result::Result<tuple<>, irust::irust::irust_error::IRustError>::expect<tuple<>,irust::irust::irust_error::IRustError>
             at C:\Users\username\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:963
  14: irust::main
             at .\src\main.rs:19
  15: std::rt::lang_start::{{closure}}<tuple<>>
             at C:\Users\username\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
  17: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
  18: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
  19: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
  20: std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
  21: std::rt::lang_start<tuple<>>
             at C:\Users\username\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  22: main
  23: invoke_main
             at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: __scrt_common_main_seh
             at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sigmaSd** [comment]
Thanks for testing.

Apparently I do some basic checking here https://github.com/sigmaSd/IRust/blob/master/src/irust/repl.rs#L22 for file corruption (maybe your editor format the file to be less then 2 lines ?), I forgot why I added it though

Can you try after commenting that out?

**Comment by fdncred** [comment]
I do have `formatOnSave` set to true for `rust` files - so formatting could look different. Let me know when it's ready to test again.

**Comment by fdncred** [comment]
oh, i'm sorry - i misunderstood. you want me to comment that out and try again - ok. hold on.

**Comment by sigmaSd** [comment]
I suspect something else is going on here, so it would be great if you add
dbg!(&main_file) there and run with cargo r 2>log

**Comment by fdncred** [comment]
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `C:\Cargo\Target\debug\irust.exe`
[src\irust\repl.rs:22] &main_file = "fn main() {\n    fn factorial(n: usize) -> usize {\n        match n {\n            1 => 1,\n            n => n * factorial(n - 1),\n        }\n    }\n}\n"
[src\irust\repl.rs:22] &main_file = "fn main() {\n    fn factorial(n: usize) -> usize {\n        match n {\n            1 => 1,\n            n => n * factorial(n - 1),\n        }\n    }\n}\n"
[src\irust\repl.rs:22] &main_file = "fn main() {\n    fn factorial(n: usize) -> usize {\n        match n {\n            1 => 1,\n            n => n * factorial(n - 1),\n        }\n    }\n}\n"
[src\irust\repl.rs:22] &main_file = ""
thread 'main' panicked at 'attempt to subtract with overflow', src\irust\repl.rs:28:26
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
   9: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
  10: std::panicking::begin_panic_handler
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
  11: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:85
  12: core::panicking::panic
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:50
  13: irust::irust::repl::Repl::update_from_main_file
             at .\src\irust\repl.rs:28
  14: irust::irust::IRust::sync
             at .\src\irust\parser.rs:341
  15: irust::irust::IRust::run
             at .\src\irust.rs:114
  16: irust::main
             at .\src\main.rs:19
  17: std::rt::lang_start::{{closure}}<tuple<>>
             at C:\Users\username\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
  19: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
  20: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
  21: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
  22: std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
  23: std::rt::lang_start<tuple<>>
             at C:\Users\username\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  24: main
  25: invoke_main
             at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  26: __scrt_common_main_seh
             at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  27: BaseThreadInitThunk
  28: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Cargo\Target\debug\irust.exe` (exit code: 101)
```

**Comment by sigmaSd** [comment]
Ah I can reproduce, I'll debug it and report back (Its probably due to somethings accessing the file at the same time)

**Comment by sigmaSd** [comment]
So from the log I see it worked 3 times and then it didn't, its very likely conflicting with cargo fmt invoked by format_on_save

**Comment by sigmaSd** [comment]
Adding a retry fix this race
```rust
    	let mut tryf = 0;
		let main_file = loop {
        let main_file = std::fs::read_to_string(&*MAIN_FILE_EXTERN)?;
        if !main_file.is_empty() || tryf > 3 {
        	break main_file
        } else {
        	tryf +=1;
        }
        };
```
Whats annoying about this issue is std::fs::read_to_string() is returning an empty string instead of an error!!

**Comment by sigmaSd** [comment]
A try with thread sleep seems to fix it I'll push it so you  can test

**Comment by sigmaSd** [comment]
I think this should fix it for now, while investigate `read_to_string` behaviour

**Comment by fdncred** [comment]
Seems to be working great for me now. I wonder if it has something to do with me saving and then closing. So, the watch was triggered on the save but then it took a few seconds for me to close the file.

**Comment by sigmaSd** [comment]
I think its something to do with vscode in particular, I don't have this issue with atom for example, Maybe somehow when saving vscode first empties the file.
The fact that its the same behaviour in linux and windows makes the culprit very likely vscode itself.

**Comment by sigmaSd** [comment]
Found it! indeed its vscode behaviour
code use node to write file and node truncate files before save, in that window of time `read_to_string` function read it as empty

https://github.com/microsoft/vscode/issues/97768#issuecomment-628681879

**Comment by sigmaSd** [comment]
@fdncred Jjust want to let you know that I remove autosync, so now if you use `:edit` with vscode you will need to use `:sync` after.
The reasons:
- notify is a big dependency
- it created unneeded complexity in the code base
- This is not an essential feature of a repl
- sync command is not that bad

Also I think the original issue is fixed with using cargo check on the input.

Hopefully this is an ok compromise.

**Comment by fdncred** [comment]
I'm sure if I have a problem with it, I'll come here to complain. :) Thanks for the heads-up. The only problem I have conceptually is remembering to `:sync`. Hopefully I can remember that the next time I use it.

**Comment by sigmaSd** [comment]
I just noticed that I disabled this, re-enabled again https://github.com/sigmaSd/IRust/commit/1ba5588da39191b4e0f1476d13023b378df274b0

Btw I think your use case is better served  with `:add` command, basicly it goes like this 
- create a new rust project
- open irust and run `:add $path_to_project`

Now you can modify the project in vscode and any change will be reflected on irust on save, with the benefit that all the normal flow works (rust-analyzer, adding crates)

Here is a demo https://sigmasd.github.io/irust_book/interactive-usage/

**Comment by sigmaSd** [comment]
I just noticed that `git tag` actually correctly uses vscode synchronously

It does this

- Open a new tab in vscode
- Wait for the tab to be closed 
- Continue after that

I'll add investigating this to `todo`

**Pull request merged**
