### PR TITLE
irust script: support mix commands with rust codes

### PR DESCRIPTION
**Pull request by light4**
Add an irust plugin to support mix commands with rust codes, see also #95 
for example:

```rust
In: pub fn test() {
In:     println!("test");
In: }
In:  :expand test
In: pub fn another -> usize {
In:     42
In: }
In: :asm another
```
before:
before

after:
after

### CODE REVIEW

**Comment by sigmaSd** [comment]
first thanks a lot that's pretty cool

So I added a commit here https://github.com/sigmaSd/IRust/pull/96/commits/a32baeab7dbaa0c663960cc62af50dcf74e18980 that does:

1- hoist output_event_hook to be just at the end of enter, I think that's where it belongs
2- change back parse to Parse(String), it seems to work without needing to add more variables there
3- fix a bug in split_cmds where there was leftover in tmp_vec
4- remove the on logic, because the user can already use `:scripts MixedCmds deactivate` and `:scripts MixedCmds activate`

**Comment by sigmaSd** [comment]
Please test it and report back what do you think

**Comment by light4** [comment]
These changes are great.
But I find a bug during the test, although it is not related to this PR. If both `Fun` and `MixedCmds` are activated, plugins will not work properly.

```rust
In: :scripts
Name    ScriptType      Hooks   State

Fun     Daemon  ["OutputEvent", "Shutdown"]     true
MixedCmds       Daemon  ["OutputEvent", "Shutdown"]     true

In: fn test() {
..:     println!("test");
..: }
..:  :expand test
..: pub fn another() -> usize {
..:     42
..: }
..: :asm another
error: expected expression, found `:`
 --> src/main.rs:6:2
  |
6 |  :expand test
  |  ^ expected expression


```

**Comment by sigmaSd** [comment]
Script interaction if they listen to the same hook is something I'm currently still undecided about.
What I currently do is just execute the first answer from the hook https://github.com/sigmaSd/IRust/blob/master/crates/irust/src/irust/script/script_manager.rs#L137

I can make them work at the same time by modifying that function but the output I feel looks weird
image


I think this is something to figure in the future and definitely not a blocker for this pr, if you agree I can merge this.

**Comment by light4** [comment]
Merge this please. We can fix the issue later.

**Comment by sigmaSd** [comment]
thanks!

**Pull request merged**
